### ISSUE TITLE
Opção de Logout

### ISSUE THREAD

**Issue by rochacon** [xupisco/MoneyLog-Cloud#1]
Aparentemente não existe uma forma de fazer logout do Moneylog Cloud. O que acontece é que, após acessar uma vez, permaneço logado no http://moneylog-cloud.aurelio.net. (Pelo menos até que eu faça um novo login com outra conta).

**Comment by xupisco** [comment]
Oi Rochacon... acontece que não existe login no Moneylog Cloud, e sim no Dropbox! A única maneira de desconectar é sair também do Dropbox, ok?

[]'s

**Comment by rochacon** [comment]
Perfeito, mas mesmo saindo do Dropbox o token de autenticação continua salvo e funcionando, pois os cookies do Moneylog (especificadamente, 'access_token_key') não foram removidos. A opção de logout removeria os cookies e a sessão do usuário (caso exista). Dessa forma, no próximo login não existirá sessão ativa e o usuário é redirecionado para a página de login.

Exemplo de replicação:
1. Login no Moneylog Cloud / Dropbox
2. Logout do Dropbox
3. Recarregue o Moneylog Cloud (continua ativo)

**Comment by xupisco** [comment]
Opa, incluimos o link "Logout" no final do sidebar... Se tiver alguma dúvida ou problema é só falar!
[]'s
