### ISSUE TITLE
Passo a passo para instalação

### ISSUE THREAD

**Issue by rogeriopradoj** [xupisco/MoneyLog-Cloud#3]
Olá, @xupisco e @oreio , parabéns pelo trabalho de vocês dois.

Gostaria de pedir um passo a passo para instalação do moneylog-cloud num servidor próprio (localhost mesmo, talvez depois passando para um servidor pessoal).

É que não trabalho com Python, se tivesse disponível aqui um tutorial bacana de como instalar essa versão cloud ajudaria bastante.

Valeu,

**Comment by xupisco** [comment]
Oi Rogério,
o MoneyLog Cloud funciona exclusivamente com o Dropbox... em nenhum momento os arquivos são acessados / escritos direto no sistema, mesmo que tenha o Dropbox instalado na máquina!

Você pode se basear na versão Cloud e adapta-la para um server local.
[]'s

**Comment by rogeriopradoj** [comment]
Oi @xupisco , essa parte eu entendi :).

Mas o que eu queria se tivesse é um passo a passo de como colocar no meu server local.

É que eu trabalho com PHP, e se o projeto fosse nessa linguagem meu passo a passo seria algo assim:
- instale um servidor xAMP (Apache com o módulo PHP).
- descompacte os arquivos do projeto na web root do seu servidor web (geralmente htdocs ou www)
- faça uma cópia do arquivo config.php.example para config.php
- configure o APP ID do dropbox no config.php
- acesse no seu navegador em http://localhost/MoneyLog-Cloud/ ou se http://www.example.com/MoneyLog-Cloud/

Pegou a idéia?

Eu achei muito bacana essa iniciativa do @oreio de colocar o projeto hospedado no servidor dele, e de graça!

Mas como outras pessoas já falaram, a falta de conexão segura SSL é um problema para os momentos que não estamos em redes tão seguras. Como tenho um servidor meu (que roda Python, mesmo eu não sabendo usar :-P), gostaria de colocar para funcionar lá usando SSL, entendeu?

**Comment by xupisco** [comment]
Oio Rogério,
infelizmente não tenho pronto nenhum tut para fazer o mesmo em PHP (acho que nem lembro mais como programa nisso... :P).

Sobre o SSL:
O Aurelio disponibiliza o domínio, todo o projeto roda e está hospedado no Google (appengine), vc pode acessá-lo por HTTPS via https://moneylog-cloud.appspot.com/

[]'s

**Comment by rogeriopradoj** [comment]
Na verdade eu não quero um tut para rodar em PHP.

Eu queria um para rodar em Python!!!

**Comment by rogeriopradoj** [comment]
Ah, e o domínio que você passou do Aurélio, depois do login, redireciona pra http://moneylog-cloud.aurelio.net/.

Mas beleza cara, valeu pela atenção pelo menos :-)

[]'s

P.S.: Se puder colocar um tut mais completo de como rodar no Python essa aplicação, :)

**Comment by aureliojargas** [comment]
Rogério, a gente usa o App Engine do Google, que cuida de toda a infra e dá um ambiente Python pronto para usar. Eu não saberia como replicar este ambiente "na mão" num servidor local. Outra alternativa é você criar uma conta lá no App Engine e hospedar lá uma cópia do projeto.

**Comment by rogeriopradoj** [comment]
Valeu Aurélio!
