### ISSUE TITLE
API v1 do Dropbox vai sair do ar :(

### ISSUE THREAD

**Issue by aureliojargas** [xupisco/MoneyLog-Cloud#6]
https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

A data limite é 28/06/2017, está perto. Será que é muito trampo atualizar pra nova?

**Comment by xupisco** [comment]
Grande @aureliojargas, tudo bão? Como vai o muleque?

Óia, nem tinha visto isso... não uso mais o Dropbox (e consequentemente o MoneyLog) :(
Vou dar uma olhada no que precisa mudar e te falo!

[]'s

**Comment by aureliojargas** [comment]
Bem, vou fechar essa issue já que a outra #7 tem mais informações
